apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-app
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: fastfood-app
          image: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/fastfood-app:prod
